In [6]:
import numpy as np

def get_nonzero_grid(array, padding=0):
    # Find indices of nonzero elements
    nonzero_indices = np.nonzero(array)

    # Get the bounding box of nonzero elements
    min_row, max_row = np.min(nonzero_indices[0]), np.max(nonzero_indices[0])
    min_col, max_col = np.min(nonzero_indices[1]), np.max(nonzero_indices[1])

    # Add padding to the bounding box
    min_row_pad = max(min_row - padding, 0)
    max_row_pad = min(max_row + padding + 1, array.shape[0])
    min_col_pad = max(min_col - padding, 0)
    max_col_pad = min(max_col + padding + 1, array.shape[1])

    # Extract the grid with padding
    grid_with_padding = array[min_row_pad:max_row_pad, min_col_pad:max_col_pad]

    return grid_with_padding

# Example usage
arr = np.array([
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0]
])

grid_snapshot = get_nonzero_grid(arr, padding=2)
print(grid_snapshot)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
